// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/comment/comment.proto

package comment_service // import "rpc/comment/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommentInfo struct {
	ArticleId            int64    `protobuf:"varint,1,opt,name=article_id,json=articleId" json:"article_id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	CommentId            int64    `protobuf:"varint,3,opt,name=comment_id,json=commentId" json:"comment_id,omitempty"`
	PCommentId           int64    `protobuf:"varint,4,opt,name=p_comment_id,json=pCommentId" json:"p_comment_id,omitempty"`
	ReplyUid             int64    `protobuf:"varint,5,opt,name=reply_uid,json=replyUid" json:"reply_uid,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentInfo) Reset()         { *m = CommentInfo{} }
func (m *CommentInfo) String() string { return proto.CompactTextString(m) }
func (*CommentInfo) ProtoMessage()    {}
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_448bd877a7ebf785, []int{0}
}
func (m *CommentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentInfo.Unmarshal(m, b)
}
func (m *CommentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentInfo.Marshal(b, m, deterministic)
}
func (dst *CommentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentInfo.Merge(dst, src)
}
func (m *CommentInfo) XXX_Size() int {
	return xxx_messageInfo_CommentInfo.Size(m)
}
func (m *CommentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CommentInfo proto.InternalMessageInfo

func (m *CommentInfo) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

func (m *CommentInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CommentInfo) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *CommentInfo) GetPCommentId() int64 {
	if m != nil {
		return m.PCommentId
	}
	return 0
}

func (m *CommentInfo) GetReplyUid() int64 {
	if m != nil {
		return m.ReplyUid
	}
	return 0
}

func (m *CommentInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ReplyInfo struct {
	Comment              *CommentInfo `protobuf:"bytes,1,opt,name=comment" json:"comment,omitempty"`
	Reply                *CommentInfo `protobuf:"bytes,2,opt,name=reply" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyInfo) Reset()         { *m = ReplyInfo{} }
func (m *ReplyInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyInfo) ProtoMessage()    {}
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_448bd877a7ebf785, []int{1}
}
func (m *ReplyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyInfo.Unmarshal(m, b)
}
func (m *ReplyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyInfo.Marshal(b, m, deterministic)
}
func (dst *ReplyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyInfo.Merge(dst, src)
}
func (m *ReplyInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyInfo.Size(m)
}
func (m *ReplyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyInfo proto.InternalMessageInfo

func (m *ReplyInfo) GetComment() *CommentInfo {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *ReplyInfo) GetReply() *CommentInfo {
	if m != nil {
		return m.Reply
	}
	return nil
}

type LikeInfo struct {
	ArticleId            int64    `protobuf:"varint,1,opt,name=article_id,json=articleId" json:"article_id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeInfo) Reset()         { *m = LikeInfo{} }
func (m *LikeInfo) String() string { return proto.CompactTextString(m) }
func (*LikeInfo) ProtoMessage()    {}
func (*LikeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_448bd877a7ebf785, []int{2}
}
func (m *LikeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeInfo.Unmarshal(m, b)
}
func (m *LikeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeInfo.Marshal(b, m, deterministic)
}
func (dst *LikeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeInfo.Merge(dst, src)
}
func (m *LikeInfo) XXX_Size() int {
	return xxx_messageInfo_LikeInfo.Size(m)
}
func (m *LikeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LikeInfo proto.InternalMessageInfo

func (m *LikeInfo) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

func (m *LikeInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetCountRequest struct {
	ArticleIds           []int64  `protobuf:"varint,1,rep,packed,name=article_ids,json=articleIds" json:"article_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCountRequest) Reset()         { *m = GetCountRequest{} }
func (m *GetCountRequest) String() string { return proto.CompactTextString(m) }
func (*GetCountRequest) ProtoMessage()    {}
func (*GetCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_448bd877a7ebf785, []int{3}
}
func (m *GetCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountRequest.Unmarshal(m, b)
}
func (m *GetCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountRequest.Marshal(b, m, deterministic)
}
func (dst *GetCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountRequest.Merge(dst, src)
}
func (m *GetCountRequest) XXX_Size() int {
	return xxx_messageInfo_GetCountRequest.Size(m)
}
func (m *GetCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountRequest proto.InternalMessageInfo

func (m *GetCountRequest) GetArticleIds() []int64 {
	if m != nil {
		return m.ArticleIds
	}
	return nil
}

type GetCountResponse struct {
	LikeCount            map[int64]int64 `protobuf:"bytes,1,rep,name=like_count,json=likeCount" json:"like_count,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetCountResponse) Reset()         { *m = GetCountResponse{} }
func (m *GetCountResponse) String() string { return proto.CompactTextString(m) }
func (*GetCountResponse) ProtoMessage()    {}
func (*GetCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_448bd877a7ebf785, []int{4}
}
func (m *GetCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountResponse.Unmarshal(m, b)
}
func (m *GetCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountResponse.Marshal(b, m, deterministic)
}
func (dst *GetCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountResponse.Merge(dst, src)
}
func (m *GetCountResponse) XXX_Size() int {
	return xxx_messageInfo_GetCountResponse.Size(m)
}
func (m *GetCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountResponse proto.InternalMessageInfo

func (m *GetCountResponse) GetLikeCount() map[int64]int64 {
	if m != nil {
		return m.LikeCount
	}
	return nil
}

type GetCommentListRequest struct {
	ArticleId            int64    `protobuf:"varint,1,opt,name=article_id,json=articleId" json:"article_id,omitempty"`
	Cursor               int64    `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommentListRequest) Reset()         { *m = GetCommentListRequest{} }
func (m *GetCommentListRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommentListRequest) ProtoMessage()    {}
func (*GetCommentListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_448bd877a7ebf785, []int{5}
}
func (m *GetCommentListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentListRequest.Unmarshal(m, b)
}
func (m *GetCommentListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentListRequest.Marshal(b, m, deterministic)
}
func (dst *GetCommentListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentListRequest.Merge(dst, src)
}
func (m *GetCommentListRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommentListRequest.Size(m)
}
func (m *GetCommentListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentListRequest proto.InternalMessageInfo

func (m *GetCommentListRequest) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

func (m *GetCommentListRequest) GetCursor() int64 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *GetCommentListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetCommentListResponse struct {
	Reply                map[int64]*ReplyInfo `protobuf:"bytes,1,rep,name=reply" json:"reply,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HasMore              bool                 `protobuf:"varint,2,opt,name=has_more,json=hasMore" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetCommentListResponse) Reset()         { *m = GetCommentListResponse{} }
func (m *GetCommentListResponse) String() string { return proto.CompactTextString(m) }
func (*GetCommentListResponse) ProtoMessage()    {}
func (*GetCommentListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_448bd877a7ebf785, []int{6}
}
func (m *GetCommentListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentListResponse.Unmarshal(m, b)
}
func (m *GetCommentListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentListResponse.Marshal(b, m, deterministic)
}
func (dst *GetCommentListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentListResponse.Merge(dst, src)
}
func (m *GetCommentListResponse) XXX_Size() int {
	return xxx_messageInfo_GetCommentListResponse.Size(m)
}
func (m *GetCommentListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentListResponse proto.InternalMessageInfo

func (m *GetCommentListResponse) GetReply() map[int64]*ReplyInfo {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *GetCommentListResponse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

type PublishCommentRequest struct {
	CommentInfo          *CommentInfo `protobuf:"bytes,1,opt,name=comment_info,json=commentInfo" json:"comment_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PublishCommentRequest) Reset()         { *m = PublishCommentRequest{} }
func (m *PublishCommentRequest) String() string { return proto.CompactTextString(m) }
func (*PublishCommentRequest) ProtoMessage()    {}
func (*PublishCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_448bd877a7ebf785, []int{7}
}
func (m *PublishCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishCommentRequest.Unmarshal(m, b)
}
func (m *PublishCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishCommentRequest.Marshal(b, m, deterministic)
}
func (dst *PublishCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishCommentRequest.Merge(dst, src)
}
func (m *PublishCommentRequest) XXX_Size() int {
	return xxx_messageInfo_PublishCommentRequest.Size(m)
}
func (m *PublishCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishCommentRequest proto.InternalMessageInfo

func (m *PublishCommentRequest) GetCommentInfo() *CommentInfo {
	if m != nil {
		return m.CommentInfo
	}
	return nil
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_448bd877a7ebf785, []int{8}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (dst *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(dst, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type LikePointRequest struct {
	LikeInfo             *LikeInfo `protobuf:"bytes,1,opt,name=like_info,json=likeInfo" json:"like_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LikePointRequest) Reset()         { *m = LikePointRequest{} }
func (m *LikePointRequest) String() string { return proto.CompactTextString(m) }
func (*LikePointRequest) ProtoMessage()    {}
func (*LikePointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_448bd877a7ebf785, []int{9}
}
func (m *LikePointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikePointRequest.Unmarshal(m, b)
}
func (m *LikePointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikePointRequest.Marshal(b, m, deterministic)
}
func (dst *LikePointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikePointRequest.Merge(dst, src)
}
func (m *LikePointRequest) XXX_Size() int {
	return xxx_messageInfo_LikePointRequest.Size(m)
}
func (m *LikePointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LikePointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LikePointRequest proto.InternalMessageInfo

func (m *LikePointRequest) GetLikeInfo() *LikeInfo {
	if m != nil {
		return m.LikeInfo
	}
	return nil
}

type GetLikeStateRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	ArticleIds           []int64  `protobuf:"varint,2,rep,packed,name=article_ids,json=articleIds" json:"article_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLikeStateRequest) Reset()         { *m = GetLikeStateRequest{} }
func (m *GetLikeStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetLikeStateRequest) ProtoMessage()    {}
func (*GetLikeStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_448bd877a7ebf785, []int{10}
}
func (m *GetLikeStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLikeStateRequest.Unmarshal(m, b)
}
func (m *GetLikeStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLikeStateRequest.Marshal(b, m, deterministic)
}
func (dst *GetLikeStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLikeStateRequest.Merge(dst, src)
}
func (m *GetLikeStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetLikeStateRequest.Size(m)
}
func (m *GetLikeStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLikeStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLikeStateRequest proto.InternalMessageInfo

func (m *GetLikeStateRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetLikeStateRequest) GetArticleIds() []int64 {
	if m != nil {
		return m.ArticleIds
	}
	return nil
}

type GetLikeStateResponse struct {
	Ok                   map[int64]bool `protobuf:"bytes,1,rep,name=ok" json:"ok,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetLikeStateResponse) Reset()         { *m = GetLikeStateResponse{} }
func (m *GetLikeStateResponse) String() string { return proto.CompactTextString(m) }
func (*GetLikeStateResponse) ProtoMessage()    {}
func (*GetLikeStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_448bd877a7ebf785, []int{11}
}
func (m *GetLikeStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLikeStateResponse.Unmarshal(m, b)
}
func (m *GetLikeStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLikeStateResponse.Marshal(b, m, deterministic)
}
func (dst *GetLikeStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLikeStateResponse.Merge(dst, src)
}
func (m *GetLikeStateResponse) XXX_Size() int {
	return xxx_messageInfo_GetLikeStateResponse.Size(m)
}
func (m *GetLikeStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLikeStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLikeStateResponse proto.InternalMessageInfo

func (m *GetLikeStateResponse) GetOk() map[int64]bool {
	if m != nil {
		return m.Ok
	}
	return nil
}

func init() {
	proto.RegisterType((*CommentInfo)(nil), "comment.CommentInfo")
	proto.RegisterType((*ReplyInfo)(nil), "comment.ReplyInfo")
	proto.RegisterType((*LikeInfo)(nil), "comment.LikeInfo")
	proto.RegisterType((*GetCountRequest)(nil), "comment.GetCountRequest")
	proto.RegisterType((*GetCountResponse)(nil), "comment.GetCountResponse")
	proto.RegisterMapType((map[int64]int64)(nil), "comment.GetCountResponse.LikeCountEntry")
	proto.RegisterType((*GetCommentListRequest)(nil), "comment.GetCommentListRequest")
	proto.RegisterType((*GetCommentListResponse)(nil), "comment.GetCommentListResponse")
	proto.RegisterMapType((map[int64]*ReplyInfo)(nil), "comment.GetCommentListResponse.ReplyEntry")
	proto.RegisterType((*PublishCommentRequest)(nil), "comment.PublishCommentRequest")
	proto.RegisterType((*EmptyResponse)(nil), "comment.EmptyResponse")
	proto.RegisterType((*LikePointRequest)(nil), "comment.LikePointRequest")
	proto.RegisterType((*GetLikeStateRequest)(nil), "comment.GetLikeStateRequest")
	proto.RegisterType((*GetLikeStateResponse)(nil), "comment.GetLikeStateResponse")
	proto.RegisterMapType((map[int64]bool)(nil), "comment.GetLikeStateResponse.OkEntry")
}

func init() {
	proto.RegisterFile("proto/comment/comment.proto", fileDescriptor_comment_448bd877a7ebf785)
}

var fileDescriptor_comment_448bd877a7ebf785 = []byte{
	// 699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdd, 0x4e, 0x1b, 0x3d,
	0x10, 0xd5, 0x26, 0x40, 0x92, 0x09, 0x7f, 0x9f, 0x3f, 0x40, 0x21, 0x14, 0x88, 0x56, 0xaa, 0x14,
	0x71, 0xb1, 0x95, 0x52, 0xa1, 0x56, 0xa5, 0x6a, 0x2b, 0x52, 0x1a, 0x50, 0xa9, 0x4a, 0x17, 0xf5,
	0xa6, 0x37, 0x51, 0xd8, 0x4c, 0xca, 0x2a, 0x9b, 0xf5, 0xd6, 0x76, 0x90, 0x72, 0xdf, 0x97, 0xe8,
	0x8b, 0xf4, 0x05, 0xfa, 0x02, 0x7d, 0xa4, 0xca, 0x5e, 0xdb, 0xd9, 0x05, 0x02, 0x12, 0x5c, 0xc5,
	0x33, 0x9e, 0x39, 0xf6, 0x9c, 0x73, 0xbc, 0x81, 0xad, 0x84, 0x51, 0x41, 0x9f, 0x05, 0x74, 0x34,
	0xc2, 0x58, 0x98, 0x5f, 0x4f, 0x65, 0x49, 0x49, 0x87, 0xee, 0x6f, 0x07, 0xaa, 0xed, 0x74, 0x7d,
	0x12, 0x0f, 0x28, 0xd9, 0x06, 0xe8, 0x31, 0x11, 0x06, 0x11, 0x76, 0xc3, 0x7e, 0xcd, 0x69, 0x38,
	0xcd, 0xa2, 0x5f, 0xd1, 0x99, 0x93, 0x3e, 0x59, 0x85, 0xe2, 0x38, 0xec, 0xd7, 0x0a, 0x2a, 0x2f,
	0x97, 0xb2, 0x41, 0x63, 0xc9, 0x86, 0x62, 0xda, 0xa0, 0x33, 0x27, 0x7d, 0xd2, 0x80, 0xc5, 0xa4,
	0x9b, 0x29, 0x98, 0x53, 0x05, 0x90, 0xb4, 0x6d, 0xc5, 0x16, 0x54, 0x18, 0x26, 0xd1, 0xa4, 0x2b,
	0x81, 0xe7, 0xd5, 0x76, 0x59, 0x25, 0xbe, 0x86, 0x7d, 0x52, 0x83, 0x52, 0x40, 0x63, 0x81, 0xb1,
	0xa8, 0x2d, 0x34, 0x9c, 0x66, 0xc5, 0x37, 0xa1, 0xfb, 0x1d, 0x2a, 0xbe, 0xac, 0x52, 0xb7, 0xf6,
	0xc0, 0x0c, 0xa4, 0xae, 0x5c, 0x6d, 0xad, 0x79, 0x66, 0xde, 0xcc, 0x70, 0xbe, 0x29, 0x22, 0x7b,
	0x30, 0xaf, 0x8e, 0x50, 0x83, 0xcc, 0xaa, 0x4e, 0x4b, 0xdc, 0x03, 0x28, 0x9f, 0x86, 0x43, 0x7c,
	0x10, 0x3b, 0x6e, 0x0b, 0x56, 0x3a, 0x28, 0xda, 0x74, 0x1c, 0x0b, 0x1f, 0x7f, 0x8c, 0x91, 0x0b,
	0xb2, 0x0b, 0xd5, 0x29, 0x06, 0xaf, 0x39, 0x8d, 0xa2, 0x24, 0xc4, 0x82, 0x70, 0xf7, 0x97, 0x03,
	0xab, 0xd3, 0x26, 0x9e, 0xd0, 0x98, 0x23, 0xe9, 0x00, 0x44, 0xe1, 0x10, 0xbb, 0x81, 0xcc, 0xaa,
	0xa6, 0x6a, 0xab, 0x69, 0xaf, 0x7d, 0xbd, 0xdc, 0x93, 0x37, 0x56, 0x99, 0xa3, 0x58, 0xb0, 0x89,
	0x5f, 0x89, 0x4c, 0x5c, 0x7f, 0x0d, 0xcb, 0xf9, 0x4d, 0x79, 0xeb, 0x21, 0x4e, 0xf4, 0x34, 0x72,
	0x49, 0xd6, 0x60, 0xfe, 0xaa, 0x17, 0x8d, 0x51, 0x4f, 0x92, 0x06, 0xaf, 0x0a, 0x2f, 0x1d, 0x77,
	0x00, 0xeb, 0xea, 0x2c, 0x75, 0xec, 0x69, 0xc8, 0xed, 0x54, 0xf7, 0x30, 0xb3, 0x01, 0x0b, 0xc1,
	0x98, 0x71, 0xca, 0x34, 0xa4, 0x8e, 0x64, 0x9e, 0x0e, 0x06, 0x1c, 0x85, 0x76, 0x8e, 0x8e, 0xdc,
	0x3f, 0x0e, 0x6c, 0x5c, 0x3f, 0x48, 0x33, 0xf1, 0xce, 0x68, 0x97, 0x92, 0xb0, 0x97, 0x27, 0xe1,
	0x46, 0xbd, 0xa7, 0x5c, 0x92, 0xd2, 0x90, 0x36, 0x92, 0x4d, 0x28, 0x5f, 0xf6, 0x78, 0x77, 0x44,
	0x59, 0x3a, 0x61, 0xd9, 0x2f, 0x5d, 0xf6, 0xf8, 0x27, 0xca, 0xb0, 0x7e, 0x0a, 0x30, 0xad, 0xbf,
	0x85, 0x99, 0x66, 0x96, 0x99, 0x6a, 0x8b, 0xd8, 0xc3, 0xad, 0x17, 0xb3, 0x6c, 0x9d, 0xc1, 0xfa,
	0xd9, 0xf8, 0x22, 0x0a, 0xf9, 0xa5, 0xbe, 0x98, 0x61, 0xeb, 0x05, 0x2c, 0xda, 0x37, 0x11, 0x0f,
	0xe8, 0x9d, 0xa6, 0xad, 0x06, 0xd3, 0xc0, 0x5d, 0x81, 0xa5, 0xa3, 0x51, 0x22, 0x26, 0x66, 0x3a,
	0xf7, 0x10, 0x56, 0xa5, 0x9c, 0x67, 0x34, 0x9c, 0xa2, 0x7b, 0xa0, 0xf4, 0xce, 0x42, 0xff, 0x67,
	0xa1, 0x8d, 0x97, 0xfd, 0x72, 0xa4, 0x57, 0xee, 0x31, 0xfc, 0xdf, 0x41, 0x21, 0x37, 0xce, 0x45,
	0x4f, 0xa0, 0x81, 0xd1, 0x6e, 0x76, 0xa6, 0x6f, 0xfd, 0x9a, 0x75, 0x0b, 0x37, 0xac, 0xfb, 0xd3,
	0x81, 0xb5, 0x3c, 0x94, 0x16, 0x6d, 0x1f, 0x0a, 0x74, 0xa8, 0x15, 0x7b, 0x9a, 0x55, 0xec, 0x46,
	0xa9, 0xf7, 0x79, 0x98, 0x8a, 0x55, 0xa0, 0xc3, 0xfa, 0x3e, 0x94, 0x74, 0x78, 0x9f, 0x4b, 0xcb,
	0x19, 0xde, 0x5b, 0x7f, 0xe7, 0x60, 0x49, 0x53, 0x78, 0x8e, 0xec, 0x0a, 0x19, 0xf9, 0x02, 0xcb,
	0x79, 0x7b, 0x90, 0x9d, 0x99, 0xbe, 0x51, 0xd3, 0xd7, 0x77, 0xef, 0xf1, 0x15, 0x39, 0x86, 0xe5,
	0xbc, 0xb8, 0x19, 0xc8, 0x5b, 0x55, 0xaf, 0x6f, 0xd8, 0xfd, 0x9c, 0x86, 0xa4, 0x03, 0x4b, 0xef,
	0x31, 0x42, 0x81, 0x8f, 0x05, 0xfa, 0xa0, 0xbf, 0x36, 0x6a, 0x4f, 0xbd, 0x70, 0x52, 0xbb, 0xe5,
	0x1b, 0x91, 0x82, 0x6c, 0xce, 0xfc, 0x7a, 0x90, 0x36, 0x2c, 0x6a, 0x69, 0x1e, 0x01, 0xf2, 0xd1,
	0x82, 0x28, 0x7d, 0xc9, 0x93, 0x19, 0xb2, 0xa7, 0x40, 0xdb, 0x77, 0x9a, 0x82, 0xbc, 0x81, 0x8a,
	0xb5, 0x39, 0xd9, 0xcc, 0x99, 0x39, 0x6b, 0xfd, 0x99, 0xcc, 0xbc, 0x05, 0x68, 0xf7, 0xe2, 0x00,
	0x23, 0xd9, 0xf1, 0x00, 0x80, 0xc3, 0xc6, 0xb7, 0x1d, 0x96, 0x04, 0xf6, 0xdf, 0x34, 0xb9, 0x38,
	0x30, 0x0f, 0x98, 0x23, 0xbb, 0x0a, 0x03, 0xbc, 0x58, 0x50, 0xff, 0xac, 0xcf, 0xff, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x7a, 0x0d, 0x31, 0xd3, 0x78, 0x07, 0x00, 0x00,
}
